security:
    providers:
      chain_provider:
        chain:
            providers: [fos_userbundle, opm_fos_facebook_provider]
      fos_userbundle:
          id: fos_user.user_provider.username
      opm_fos_facebook_provider:
          id: opm.facebook.user
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        main:
          pattern: ^/
          form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
          logout:       true
          anonymous:    true
        secured_area:
          fos_facebook:
            login_path: _security_login
            check_path: _security_check
        dev:
          pattern:  ^/(_(profiler|wdt)|css|images|js)/
          security: false
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN