security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # L%PT8NoDLVjtcd9bVy$Z
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: 976df7c634c04217061079036a4d926a981b82f7, roles: [ 'ROLE_ADMINISTRATORS' ] }

    firewalls:
        dev:
            pattern:  ^/api/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
             pattern:  ^/api
             anonymous: ~
             http_basic:
                realm: "Fraud Api"

    access_control:
        - { path: ^/api, roles: ROLE_ADMINISTRATORS }
